version: '3'
services:
  php:
    build:
      context: docker/php
    volumes:
      - '.:/var/www/html'
      - './docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'
    depends_on:
      - database



  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - '.:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    depends_on:
      - php

  database:
    image: postgres:14.10
    ports:
      - 5433:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=2612
      - POSTGRES_USER=alex
      - POSTGRES_DB=testdb
      - POSTGRES_HOST=localhost