version: '3'
services:
  php:
    build:
      context: docker/php
    volumes:
      - '.:/var/www/html'
    depends_on:
      - database
    env_file:
      - .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - '.:/var/www/html'
      - './docker/nginx/conf.d:/etc/nginx/conf.d'
    depends_on:
      - php

  database:
    image: postgres:14.10
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD={$DB_PASSWORD}
      - POSTGRES_USER={$DB_USERNAME}
      - POSTGRES_DB={$DB_DATABASE}
      - POSTGRES_HOST={$DB_HOST}
      - POSTGRES_PORT={$DB_PORT}