<div class="content">
    <div class="title"><span><h2> Форма оформления заказа </h2></span></div>
    <p></p>
    <div class="form"><form action="/order" method= "POST" name="my_form">
            <label><span class="name"> Name:</span> <br />
                <input type="search"class="guest"/></label> <p></p>
            <label><span class="email"> E-mail:</span><br />
                <input type="email"class="guest"/></label><p></p>
            <label><span class="phone"> Phone:</span><br />
                <input type="search"class="guest"/></label><p></p>
            <label><span class="address"> Address:</span><br />
                <input type="text"class="guest"/></label><p></p>
            <label><span class="date"> Delivery Time:</span><br />
                <input type="date"class="guest"/></label><p></p>
            <!--или <label><span class="date"> Дата доставки:</span>
              <input type="date"/></label>-->
            <div class="bottom">
                <input type="submit" class="bottom1" value="Отправить"/>
                <input type="submit" class="bottom2" value="Очистить"/></div>
    </div>
</div>

<style>
.content {
width: 500px;
border: 1px solid white;
font-family: "Times", serif;
}
.title{
width: 500px;
height: 50px;
background: DimGrey;
text-align:center;
color: white;
padding: 8px 20px 20px;
}
.bottom{
width: 500px;
height: 40px;
background: DimGrey;
padding: 15px 20px 10px;
}
.fio::after,.email::after,.goods::after,.date::after, .number::after{
content:"*";
color:red;
}
.bottom1,.bottom2{
background: SteelGray;
font-size: 10pt;
border-radius: 5px;
border: 1px solid SteelGray;
padding: 10px 10px;
width: 100px;
font-weight:bold;
}
.guest {
width: 380px;
height: 30px;
border: 1px solid LightGrey;
}
</style>